platform :ios, '8.0'
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

def pods
#  pod 'CLKits', '~> 1.0.1'
#    pod 'CLKits/CLFaster', '~> 1.0.1'
#    pod 'CLKits/CLNetworking', '~> 1.0.1'
#    pod 'CLKits/CLPopAnimation', '~> 1.0.1'

    pod 'pop', '~> 1.0.12'
    pod 'AFNetworking', '~> 3.2.1'
    
end

target 'CLKits' do
    pods
end
