platform :ios, '8.0'
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

def pods
    pod 'AFNetworking', '~> 3.2.1'
    pod 'pop', '~> 1.0.12'
end

target 'CLKits' do
    pods
end
