platform :ios, '8.0'
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

def pods
  
    pod 'pop', '~> 1.0.12'
    pod 'AFNetworking', '~> 3.2.1'
    pod 'FMDB', '~> 2.7.5'
    
    pod 'SVProgressHUD', '~> 2.1.2'
    pod 'FTIndicator', '~> 1.2.9'
    
    pod 'TTAnalyzeLoadTime', '~> 1.0.5'
end

target 'CLKits' do
    pods
end
